### ISSUE TITLE
Necrobrowser doesn't work

### ISSUE THREAD

**Issue by saakkaas** [muraenateam/muraena#99]
When it comes triggering necrobrowser ... :

<pre>SyntaxError: Unexpected token p in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/home/user/muraena/necrobrowser/node_modules/body-parser/lib/types/json.js:169:10)<br> &nbsp; &nbsp;at parse (/home/user/muraena/necrobrowser/node_modules/body-parser/lib/types/json.js:86:15)<br> &nbsp; &nbsp;at /home/user/muraena/necrobrowser/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (/home/user/muraena/necrobrowser/node_modules/raw-body/index.js:238:16)<br> &nbsp; &nbsp;at done (/home/user/muraena/necrobrowser/node_modules/raw-body/index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/user/muraena/necrobrowser/node_modules/raw-body/index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:517:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1400:12)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</pre>

**Comment by ohpe** [comment]
That syntaxerror seems related to something wrong in the JSON file. Could you also post here the JSON configuration, please.

**Comment by vhespanha** [comment]
@saakkaas 

Necrobrowser is configured through a (json) file called profile, see:

[profile](https://muraena.phishing.click/modules/necrobrowser#profile)

Once you show us the contents of this file, we may be able to help further debugging.
